import uuid from "react-uuid";

const DOCUMENTS = {
  entityDefinition: [
    {
      id: "3ae4cf58-f06a-b353-2168-a6e27a19e7af",
      name: "RECAP",
      description: "Datos necesarios para crear un RECAP de importaciones",
      fields: [
        {
          id: "8e883779-7cf7-6aee-8d7b-0355a07b7e82",
          name: "name",
          description: "Nombre del evento",
          type: 1,
          required: true,
          widget: 1,
          dataSourceId: null,
          relatedFieldId: null,
          defatultValue: null,
        },
        {
          id: "5c38ee9c-0d47-e549-0688-3440c68f4b24",
          name: "campaign",
          description: "Campaña",
          type: 4,
          required: true,
          widget: 4,
          dataSourceId: null,
          relatedFieldId: null,
          defatultValue: null,
        },
        {
          id: "5c84e574-9d33-63b8-01e2-b81d813638de",
          name: "supplier",
          description: "Proveedor",
          type: 4,
          required: true,
          widget: 4,
          dataSourceId: null,
          relatedFieldId: null,
          defatultValue: null,
        },
        {
          id: "e9ea9197-2f9c-a7c1-bee3-4eea9c9635e1",
          name: "originCountry",
          description: "Pais origen",
          type: 4,
          required: true,
          widget: 4,
          dataSourceId: null,
          relatedFieldId: null,
          defatultValue: null,
        },
        {
          id: "078fa7c6-be48-de92-bfe0-157320189156",
          name: "destinationCountry",
          description: "Pais destino",
          type: 4,
          required: true,
          widget: 4,
          dataSourceId: null,
          relatedFieldId: null,
          defatultValue: null,
        },
        {
          id: "46d4632b-4c8d-fb71-93b3-0f7096e7496f",
          name: "originShippingPort",
          description: "Puerto origen",
          type: 4,
          required: true,
          widget: 4,
          dataSourceId: null,
          relatedFieldId: null,
          defatultValue: null,
        },
        {
          id: "93247141-6b18-c4e0-dbd2-5fddc8ab3c5d",
          name: "destinationShippingPort",
          description: "Puerto destino",
          type: 4,
          required: true,
          widget: 4,
          dataSourceId: null,
          relatedFieldId: null,
          defatultValue: null,
        },
        {
          id: "b4dd447a-d996-475e-9e39-604203bebf17",
          name: "importationType",
          description: "Tipo de importacion",
          type: 4,
          required: true,
          widget: 4,
          dataSourceId: null,
          relatedFieldId: null,
          defatultValue: null,
        },
        {
          id: "2790ff66-5875-d02a-6cb5-30192a27650c",
          name: "productionTime",
          description: "Tiempo de produccion",
          type: 4,
          required: true,
          widget: 4,
          dataSourceId: null,
          relatedFieldId: null,
          defatultValue: null,
        },
        {
          id: "c6554c2a-e7b9-04b0-b5fc-ad2e93478298",
          name: "incoterm",
          description: "Incoterm",
          type: 4,
          required: true,
          widget: 4,
          dataSourceId: null,
          relatedFieldId: null,
          defatultValue: null,
        },
        {
          id: "d0c1c86e-dc3c-c1d5-aa3e-cf226fb479f0",
          name: "currency",
          description: "Moneda",
          type: 4,
          required: true,
          widget: 4,
          dataSourceId: null,
          relatedFieldId: null,
          defatultValue: null,
        },
        {
          id: "2df5bf35-094e-7802-6036-6fe8dca0b6ac",
          name: "status",
          description: "Estado",
          type: 4,
          required: true,
          widget: 4,
        },
        {
          id: "ed203c53-7b72-01ff-99b3-3ff6105e66be",
          name: "paymentTerms",
          description: "Terminos de pago",
          type: 4,
          required: true,
          widget: 4,
          dataSourceId: null,
          relatedFieldId: null,
          defatultValue: null,
        },
        {
          id: "35e404ed-fd65-8dff-8ee0-18639191921d",
          name: "department",
          description: "Departamento",
          type: 4,
          required: true,
          widget: 4,
          dataSourceId: null,
          relatedFieldId: null,
          defatultValue: null,
        },
        {
          id: "69a68793-91a4-f981-9dad-25b058f1b441",
          name: "transportType",
          description: "Tipo de transporte",
          type: 4,
          required: true,
          widget: 4,
          dataSourceId: null,
          relatedFieldId: null,
          defatultValue: null,
        },
      ],
    },
    {
      id: "0357dd97-dba8-ff11-9b01-2880ba511cb6",
      name: "Producto",
      description: "Datos necesarios para la definicion de un producto a importar",
      fields: [
        {
          id: "fdbb0ece-9a9c-d0d6-dfe3-70adf09f46ee",
          name: "sku",
          description: "Codigo",
          type: 1,
          required: true,
          widget: 1,
          dataSourceId: null,
          relatedFieldId: null,
          defatultValue: null,
        },
        {
          id: "9e370ff6-987d-d31d-7e85-d31594003e9f",
          name: "description",
          description: "Descripcion",
          type: 1,
          required: true,
          widget: 1,
          dataSourceId: null,
          relatedFieldId: null,
          defatultValue: null,
        },
        {
          id: "2d821acc-4572-553a-ae5b-9e01de08d06e",
          name: "quantity",
          description: "Candidad",
          type: 3,
          required: true,
          widget: 2,
          dataSourceId: null,
          relatedFieldId: null,
          defatultValue: null,
        },
      ],
    },
  ],

  dataSource: [
    { id: uuid(), name: "Paises", description: "Lista de paises origen de productos importados" },
    { id: uuid(), name: "Puertos Origen", description: "Lista de puertos origen segun pais de fabricacion" },
    { id: uuid(), name: "Puertos Destino", description: "Lista de puertos destino para importacines" },
  ],

  formDefinition: [
    {
      id: uuid(),
      name: "RECAP",
      description: "Documento para importaciones",
      sections: [
        {
          name: "Cabecera de RECAP",
          entity: "71733f95-70f8-47e7-0e8a-1e91986c2928",
          relation: 1,
          id: "0b3329c3-b464-240a-41eb-31978ce3d524",
        },
        {
          name: "Lista de productos",
          entity: "0ed7b81c-c6b1-0744-74d3-e6a821051d3c",
          relation: 2,
          id: "6388bef0-95e9-8ddf-754f-0d637e5ba87d",
        },
      ],
    },
  ],

  relations: [
    { id: 1, name: "uno a uno" },
    { id: 2, name: "uno a muchos" },
  ],
};

export { DOCUMENTS };
