const STRUCTURE_TYPE_SHELVING = 1;
const STRUCTURE_TYPE_RACK = 2;
const STRUCTURE_TYPE_RACK_BASIC = 3;
const STRUCTURE_TYPE_STAGING = 4;

const PRIMITIVE_BOX = 100;
const PRIMITIVE_SPHERE = 110;
const PRIMITIVE_CONE = 130;

export {
  STRUCTURE_TYPE_SHELVING,
  STRUCTURE_TYPE_RACK,
  STRUCTURE_TYPE_RACK_BASIC,
  STRUCTURE_TYPE_STAGING,
  PRIMITIVE_BOX,
  PRIMITIVE_SPHERE,
  PRIMITIVE_CONE,
};
